### ISSUE TITLE
想请教下，有什么 url 列表可以进行爬取吗

### ISSUE THREAD

**Issue by kbrx93** [WincerChan/Hitokoto-Spider#1]
觉得一言很赞，想自己部署一个 API，但是不知道有哪些 url 可以爬取。。。

**Comment by WincerChan** [comment]
你可以 Google 一下「一言 API」关键字，我这里不太好透露具体的哪些，因为一般都不太喜欢别人爬自己的 API 😅。
所以我才特意没注明哪些可以爬取的。

**Comment by kbrx93** [comment]
哦，是这个样子的，明白了，谢谢了。
